import './globals.css';
import Link from 'next/link';
import { ReactNode } from 'react';

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Link href="/blog/abc">abc</Link>
          <Link href="/blog/def">def</Link>
          <Link href="/blog/non-existent">non-existent</Link>
        </header>
        {children}
      </body>
    </html>
  );
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
